### ISSUE TITLE
If you click the main logo you get the default cupper site styling

### ISSUE THREAD

**Issue by Erioldoesdesign** [simplysecure/user_project_website#52]
When i visit this link: https://user-project.superbloom.design/ and then click the USER project logo I get redirected to https://subtle-medovik-58f1c6.netlify.app/ which has the old cupper styling.

If I then click a nav item I get the correct layout and styling e.g. https://subtle-medovik-58f1c6.netlify.app/findings/literature-review/ 

Video:

https://github.com/simplysecure/user_project_website/assets/11681324/495f7563-9240-4283-be1f-659e93c73143

**Comment by SaptakS** [comment]
I have updated the config files to update the baseurls in https://github.com/simplysecure/user_project_website/commit/9f117a13ce90c5184d9741889e31b8e26bc99326 . I think this is fixed now. Firefox was causing some weird caching for me which is why it was showing some inconsistent redirects, but when I tried incognito or after clearing the cache in my browser, it works correctly. Please confirm.

**Comment by Erioldoesdesign** [comment]
> I have updated the config files to update the baseurls in [9f117a1](https://github.com/simplysecure/user_project_website/commit/9f117a13ce90c5184d9741889e31b8e26bc99326) . I think this is fixed now. Firefox was causing some weird caching for me which is why it was showing some inconsistent redirects, but when I tried incognito or after clearing the cache in my browser, it works correctly. Please confirm.

It's fixed :D I did a little QA on incognito mode but pretty sure we're all good!

**Comment by Erioldoesdesign** [comment]
Completed - see above
